export const roomTypes = [
  "Bathroom",
  "Boardroom",
  "Break Room",
  "Closet",
  "Coat Room",
  "Copy Room",
  "Courtyard",
  "Enclave",
  "Focus Booth",
  "Kitchen",
  "Locker Room",
  "Lunch Room",
  "Mail Room",
  "Meeting Room",
  "Supply Closet"
];

export const roomNames = [
  "Ottawa",
  "Capri",
  "Gaborone",
  "Moscow",
  "Equinox",
  "popstar",
  "Prada",
  "Shake",
  "Demeter",
  "MIT",
  "Plymouth University",
  "Imagination",
  "Hera",
  "Grand Central Terminal",
  "Tegucigalpa",
  "Thought",
  "Pleiades",
  "Pumbaa",
  "Calypso",
  "Marcus Aurelius",
  "Vera Wang",
  "Rocket",
  "Lagerfeld",
  "X-Men",
  "Hermes",
  "Xavi",
  "Sphinx",
  "Tivoli",
  "Harlem",
  "Walt Disney",
  "Superman",
  "Tanker",
  "Spock",
  "Bollywood",
  "Byzantium",
  "capsule",
  "Leonidas",
  "BMW",
  "Warhol",
  "James A. Garfield",
  "Q1",
  "Mickey Mouse",
  "Lilith",
  "Metre",
  "Avitus",
  "Taipei",
  "Orange",
  "Jaguar",
  "Aladdin",
  "Sirius Black",
  "Balbinus",
  "Machu Picchu",
  "Viserys",
  "Hilfiger",
  "SpongeBob",
  "Pouter",
  "Imperial College",
  "Bern",
  "Rickon",
  "The Empire",
  "Galactic Republic",
  "Plan",
  "Gilly",
  "Belantis",
  "Robert De Niro",
  "Prague",
  "Cygnus",
  "Eiffel Tower",
  "Pippi Longstocking",
  "Luella Bartley",
  "Brown University",
  "Gallienus",
  "Jakarta",
  "Hestia",
  "Lima",
  "Deep Space Nine",
  "Commodus",
  "Gardaland",
  "Le PAL",
  "Domitian",
  "Bran",
  "Result",
  "Hector",
  "Ulysses S. Grant",
  "Aurelian",
  "Boat",
  "Success",
  "Heide- Park",
  "Garn",
  "Romulan",
  "Leadership",
  "Reason",
  "Sheppey",
  "Sydney Opera House",
  "Staten Island",
  "Helsinki",
  "Richard Nixon",
  "Anastasia",
  "Alderaan",
  "Nanoacre",
  "Hudson River",
  "Eureka Tower",
  "Persephone",
  "Barack Obama",
  "Batman",
  "Transamerica Pyramid",
  "Dublin",
  "Westeros",
  "Columbia",
  "Hepburn",
  "Caretaker",
  "Grover Cleveland",
  "Plaza 66",
  "Upper East Side",
  "Chrysler Building",
  "Woodrow Wilson",
  "Carlos Tevez",
  "First Order",
  "George H. W. Bush",
  "Neelix",
  "Paris",
  "Coruscant",
  "Abraham Lincoln",
  "Productivity",
  "Jonathan Archer",
  "Santi Cazorla",
  "Choo",
  "Lamborghini",
  "Paramount Pictures",
  "Cobalt",
  "Ship",
  "Effectiveness",
  "George Washington",
  "Landmark Tower",
  "Drayton Manor",
  "Whaleboat",
  "Aphrodite",
  "Submarine",
  "Black",
  "Neymar",
  "Scooby-Doo",
  "Priam",
  "Bilbo Baggins",
  "USS Voyager",
  "Caracalla",
  "Poseidon",
  "Tacitus",
  "Phineas",
  "Amaranth",
  "Mr. Tumnus",
  "Bullerby",
  "Melisandre",
  "Mansfield",
  "Louvre",
  "New Hope",
  "Kobi",
  "Peugeot",
  "Andrew Jackson",
  "Versace",
  "Empire State Building",
  "Leia",
  "Manny",
  "Peleus",
  "James T. Kirk",
  "Orbit",
  "Porsche",
  "Flame",
  "Volvo",
  "Claudio Bravo",
  "PortAventura",
  "Hansa- Park",
  "Friedman",
  "Lyndon B. Johnson",
  "Athens",
  "Andromeda Galaxy",
  "Woody Allen",
  "Achilles",
  "Odysseus",
  "World Trade Center",
  "Aragorn",
  "Arjen Robben",
  "Belgrade",
  "Manila",
  "Canberra",
  "Gemini",
  "Sid",
  "Taipei 101",
  "Davos",
  "Versailles",
  "Legoland",
  "Pisces",
  "Atalanta",
  "Chevrolet",
  "Augustus",
  "Eggplant",
  "Theon Greyjoy",
  "Lewandowski",
  "Hermione",
  "Kelly",
  "Enterprise (NX-01)",
  "Muggles",
  "Coral",
  "Ford",
  "Puce",
  "Fred Zinnemann",
  "Herbert Hoover",
  "University of Winchester",
  "Grable",
  "Dietrich",
  "Big Ben",
  "Arturo Vidal",
  "Yale",
  "Earth",
  "Sofia",
  "University of Leicester",
  "Bronx",
  "Washington",
  "Wiffle",
  "Carinus",
  "Valentinian",
  "Xindi",
  "Amber",
  "Moon",
  "Astor Row",
  "London",
  "Simba",
  "Warsaw",
  "Willis Tower",
  "Neverland",
  "Revenge of the Sith",
  "Carlos Sanchez",
  "Stark",
  "Totti",
  "Zodiac",
  "Return of the Jedi",
  "Monroe",
  "Modrić",
  "Battery Park City",
  "Sukhumi",
  "Columbus Circle",
  "Voldemort",
  "University of Sunderland",
  "William Henry Harrison",
  "Aptitude",
  "Cardin",
  "Valentino",
  "Iniesta",
  "Jedi",
  "Majorian",
  "Brandenburg Gate",
  "Great Wall of China",
  "White",
  "Wheaton",
  "Strategy",
  "Galactic Senate",
  "Ygritte",
  "Gaia",
  "Riesenrad",
  "Benjamin Harrison",
  "Bardot",
  "Doctor Dolittle",
  "Yoda",
  "James Monroe",
  "Monoceros",
  "Severus",
  "Lauren",
  "Wing",
  "Akademos",
  "Mirabilandia",
  "Dartmouth",
  "Lenat",
  "Isco",
  "Trajan",
  "Mercedes",
  "Daenerys",
  "Samwell Tarly",
  "Thomas Müller",
  "Rogue One",
  "Leigh",
  "Todt Hill",
  "Stonehenge",
  "University of Buckingham",
  "Tierney",
  "Cornell",
  "Orpheus",
  "Nemo",
  "Ground Zero",
  "Kors",
  "Garbo",
  "Minion",
  "Ferb",
  "Nemesis",
  "Lombard",
  "Gandalf",
  "Creativity",
  "Solution",
  "Times Square",
  "Aircraft",
  "The Force Awakens",
  "Altuve",
  "Titus",
  "Ferrari",
  "Tantalus",
  "Hong Kong",
  "Canoe",
  "Helen",
  "Stockholm",
  "Artemis",
  "Sansa",
  "Jon Snow",
  "Andersen",
  "Aries",
  "Gucci",
  "John Tyler",
  "Folly",
  "Bazaar",
  "Padmé Amidala",
  "Bentley",
  "Familypark",
  "New Delhi",
  "Burj Khalifa",
  "Wave Lagoon",
  "Alves",
  "Starfleet",
  "Özil",
  "Ibrahimović",
  "Shrek",
  "Athena",
  "Canard",
  "Satellite",
  "Integrity",
  "Bicycle",
  "Agamemnon",
  "Jean-Luc Picard",
  "Alex Teixeira",
  "Caligula",
  "Ares",
  "Audi",
  "Howard Hawks",
  "Tatralandia",
  "Abu Dhabi",
  "Jovian",
  "MegaFonzie",
  "Arcadius",
  "Beverly Crusher",
  "Rose",
  "Hubble-barn",
  "Eclipse",
  "Queens",
  "Lusaka",
  "Havana",
  "Jiffy",
  "Libra",
  "Aquarius",
  "Claret",
  "Ronaldo",
  "Claudius",
  "Berkeley",
  "Parachute",
  "Jimmy Carter",
  "Shanghai Tower",
  "Jhane Barnes",
  "Berlin",
  "Apollo",
  "Colosseum",
  "Citroën",
  "Hubert de Givenchy",
  "Astana",
  "James Bond",
  "Dreamworld",
  "Mars",
  "Smoot",
  "Perseus",
  "Troy",
  "Stanford",
  "John F. Kennedy",
  "Vienna",
  "Barn",
  "Alfred Hitchcock",
  "Orion",
  "Dion Lee",
  "Silva",
  "Cambridge",
  "The Little Prince",
  "Hayworth",
  "Beige",
  "Hadrian",
  "Ned Stark",
  "Motivation",
  "Brooklyn",
  "Deadline",
  "Carnegie Hill",
  "Kepler",
  "Clarkson",
  "Hades",
  "Madrid",
  "Cadmus",
  "Idea",
  "Liseberg",
  "Lea",
  "Zeus",
  "Riverdale",
  "Harry",
  "Microfortnight",
  "Lovelace",
  "Microcentury",
  "shed",
  "Crawford",
  "Hundred Acre Wood",
  "Leo",
  "Jupiter",
  "Heracles",
  "Princeton",
  "Luis Suarez",
  "Epitech",
  "Greenwich Village",
  "Cerise",
  "Kingston",
  "Blush",
  "Zoomarine",
  "Donald Trump",
  "Strength",
  "ENSAT",
  "Chanel",
  "Sergio Aguero",
  "Europa-Park",
  "smitten",
  "Motorcycle",
  "Greenpoint",
  "Neptune",
  "Cinderella",
  "Taj Mahal",
  "Wellington",
  "Brasília",
  "Darth Vader",
  "Efteling",
  "Homer",
  "Millard Fillmore",
  "Rome",
  "Tommen",
  "Essos",
  "Ronald Reagan",
  "Airplane",
  "Warner Bros.",
  "Armani",
  "Power",
  "Pandora",
  "Hobbit",
  "Dwight D. Eisenhower",
  "Oslo",
  "Müller",
  "Luke Song",
  "Asterix",
  "Goal",
  "40 Wall Street",
  "Narnia",
  "Florianus",
  "Maximinus",
  "Windsor Terrace",
  "Lisbon",
  "Ron",
  "Hollywood",
  "Franklin Pierce",
  "Eileen Fisher",
  "Yves",
  "Pegasus",
  "Hogwarts",
  "Javier Mascherano",
  "Mustang",
  "SoHo",
  "United Federation of Planets",
  "Warsaw Spire",
  "Hikaru Sulu",
  "LSE",
  "Archenland",
  "James Madison",
  "Beijing",
  "Joffrey",
  "Frankenstein",
  "Tropical Island",
  "Dior",
  "Spider-Man",
  "Harvard",
  "Bill Clinton",
  "Benjamin Sisko",
  "Midtown Manhattan",
  "Gendry",
  "Tokyo",
  "Probus",
  "Obelix",
  "Charlie Chaplin",
  "University of Law",
  "Muscat",
  "Liberty Island",
  "Esiee Paris",
  "Diocletian",
  "Macrinus",
  "USS Defiant",
  "Louboutin",
  "Disneyland",
  "Amsterdam",
  "Franklin D. Roosevelt",
  "Spacecraft",
  "Aslan",
  "Kylo Ren",
  "Society",
  "Singapore",
  "Robin Hood",
  "Tatum",
  "Bangkok",
  "Yacht",
  "Inspiration",
  "Oxford",
  "Mauro Icardi",
  "Violet",
  "Messi",
  "Telerobotics",
  "Umist",
  "The Clone Wars",
  "The Shard",
  "Roosevelt Island",
  "Vespasian",
  "Prater",
  "Innovation",
  "Jacobs",
  "Sagittarius",
  "Skywalker",
  "Rooney",
  "Roman Polanski",
  "Gerald Ford",
  "Valletta",
  "Hecate",
  "UCL",
  "Peter Pan",
  "Petronas Towers",
  "Bushwick",
  "John Adams",
  "Luanda",
  "Thomas Jefferson",
  "Cardassian",
  "Puy du Fou",
  "Daimler",
  "Scotty"
];
